#include "Item/Item.hpp"
#include "Player/PlayerGet.hpp"
#include "global.h"

const u32 data_ov000_020af58c[] = {
    GIModel_None, // ItemId_Nothing
    GIModel_shdA, // ItemId_NormalShield
    GIModel_swdA, // ItemId_NormalSword
    GIModel_trnd, // ItemId_Whirlwind
    GIModel_bomb, // ItemId_BombBag
    GIModel_bowA, // ItemId_NormalBow
    GIModel_bmrn, // ItemId_Boomerang
    GIModel_whip, // ItemId_Whip
    GIModel_srod, // ItemId_SandRod
    GIModel_None, // ItemId_9
    GIModel_keyN, // ItemId_NormalKey
    GIModel_keyB, // ItemId_BossKey
    GIModel_rupG, // ItemId_GreenRupee
    GIModel_rupB, // ItemId_BlueRupee
    GIModel_rupR, // ItemId_RedRupee
    GIModel_rupG, // ItemId_BigGreenRupee
    GIModel_rupR, // ItemId_BigRedRupee
    GIModel_rupL, // ItemId_BigGoldRupee
    GIModel_frcY, // ItemId_ForceGem_18
    GIModel_frcY, // ItemId_ForceGem_19
    GIModel_frcY, // ItemId_ForceGem_20
    GIModel_litA, // ItemId_ForestGlyph
    GIModel_litB, // ItemId_SnowGlyph
    GIModel_litC, // ItemId_OceanGlyph
    GIModel_litD, // ItemId_FireGlyph
    GIModel_litA, // ItemId_25
    GIModel_litB, // ItemId_26
    GIModel_litC, // ItemId_27
    GIModel_litD, // ItemId_28
    GIModel_litC, // ItemId_29
    GIModel_litA, // ItemId_FinalTrack
    GIModel_None, // ItemId_31
    GIModel_None, // ItemId_32
    GIModel_None, // ItemId_33
    GIModel_None, // ItemId_34
    GIModel_frcY, // ItemId_ForceGem_35
    GIModel_frcY, // ItemId_ForceGem_36
    GIModel_frcY, // ItemId_ForceGem_37
    GIModel_cloA, // ItemId_RecruitUniform
    GIModel_ptmL, // ItemId_PostmasterLetter
    GIModel_hrtu, // ItemId_HeartContainer
    GIModel_apdM, // ItemId_QuiverMedium
    GIModel_bmbM, // ItemId_BombBagMedium
    GIModel_frcY, // ItemId_ForceGem_43
    GIModel_frcY, // ItemId_ForceGem_44
    GIModel_frcY, // ItemId_ForceGem_45
    GIModel_frcY, // ItemId_ForceGem_46
    GIModel_frcY, // ItemId_ForceGem_47
    GIModel_frcY, // ItemId_ForceGem_48
    GIModel_frcY, // ItemId_ForceGem_49
    GIModel_frcY, // ItemId_ForceGem_50
    GIModel_frcY, // ItemId_ForceGem_51
    GIModel_frcY, // ItemId_ForceGem_52
    GIModel_frcY, // ItemId_ForceGem_53
    GIModel_frcY, // ItemId_ForceGem_54
    GIModel_frcY, // ItemId_ForceGem_55
    GIModel_frcY, // ItemId_ForceGem_56
    GIModel_frcY, // ItemId_ForceGem_57
    GIModel_frcY, // ItemId_ForceGem_58
    GIModel_frcY, // ItemId_ForceGem_59
    GIModel_frcY, // ItemId_ForceGem_60
    GIModel_frcY, // ItemId_ForceGem_61
    GIModel_pflt, // ItemId_PanFlute
    GIModel_stmp, // ItemId_StampBook
    GIModel_bowB, // ItemId_LightBow
    GIModel_swdB, // ItemId_LokomoSword
    GIModel_przC, // ItemId_TenPriceCard
    GIModel_revR, // ItemId_RedPotion
    GIModel_revP, // ItemId_PurplePotion
    GIModel_revY, // ItemId_YellowPotion
    GIModel_mons, // ItemId_DemonFossil
    GIModel_stlb, // ItemId_StalfosSkull
    GIModel_star, // ItemId_StarFragment
    GIModel_beee, // ItemId_BeeLarvae
    GIModel_mrrn, // ItemId_WoodHeart
    GIModel_prlB, // ItemId_DarkPearlLoop
    GIModel_prlA, // ItemId_WhitePearlLoop
    GIModel_crwn, // ItemId_RutoCrown
    GIModel_zola, // ItemId_DragonScale
    GIModel_pnec, // ItemId_PirateNecklace
    GIModel_bowl, // ItemId_PalaceDish
    GIModel_glon, // ItemId_GoronAmber
    GIModel_jade, // ItemId_MysticJade
    GIModel_coin, // ItemId_AncientCoin
    GIModel_gold, // ItemId_PricelessStone
    GIModel_ring, // ItemId_RegalRing
    GIModel_arst, // ItemId_ArrowsRefill
    GIModel_bmst, // ItemId_BombsRefill
    GIModel_sold, // ItemId_SoldOutSign
    GIModel_shdB, // ItemId_AncientShield
    GIModel_apdL, // ItemId_QuiverLarge
    GIModel_bmbL, // ItemId_BombBagLarge
    GIModel_None, // ItemId_RandCommonTreasure
    GIModel_None, // ItemId_RandUncommonTreasure
    GIModel_None, // ItemId_RandRareTreasure
    GIModel_None, // ItemId_RandLegendaryTreasure
    GIModel_szku, // ItemId_TearLight
    GIModel_Lcmp, // ItemId_LightCompass
    GIModel_makA, // ItemId_ScrollSpinAttack
    GIModel_makB, // ItemId_ScrollBeam
    GIModel_ptmL, // ItemId_LinebeckLetter
    GIModel_gdpf, // ItemId_PanFluteSong_101
    GIModel_gdpf, // ItemId_PanFluteSong_102
    GIModel_gdpf, // ItemId_PanFluteSong_103
    GIModel_gdpf, // ItemId_PanFluteSong_104
    GIModel_gdpf, // ItemId_PanFluteSong_105
    GIModel_rbnt, // ItemId_RabbitNet
    GIModel_poit, // ItemId_BeedleCard
    GIModel_poiS, // ItemId_SilverCard
    GIModel_poiG, // ItemId_GoldCard
    GIModel_poiP, // ItemId_PlatinumCard
    GIModel_poiD, // ItemId_DiamondCard
    GIModel_poiF, // ItemId_FreebieCard
    GIModel_poi5, // ItemId_QuintupleCard
    GIModel_ptmL, // ItemId_CarbenLetter
    GIModel_cloA, // ItemId_RecruitUniform2
    GIModel_cloB, // ItemId_EngineerUniform
};

ARM u32 func_ov000_020a4c00(ItemId itemId) {
    return data_ov000_020af58c[itemId];
}
