#include "Cutscene/Cutscene.hpp"
#include "Unknown/UnkStruct_027e09a4.hpp"
#include "Unknown/UnkStruct_027e09b8.hpp"

const CutsceneParamsEntry gCSParamsEntries[CutsceneIndex_Max] = {
    {
        // CutsceneIndex_TitleScreen
        .mUnk_00            = "d00_01",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x00,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x00,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0048,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_Intro
        .mUnk_00            = "d02_01",
        .mSceneIndex        = SceneIndex_f_first,
        .mRoomIndex         = 0x0A,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x01,
        .mNextSceneIndex    = SceneIndex_f_first,
        .mNextRoomIndex     = 0x0A,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = true,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0049,
        .mFlag              = AdventureFlag_WatchedIntroCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d03_01
        .mUnk_00            = "d03_01",
        .mSceneIndex        = SceneIndex_f_hyral,
        .mRoomIndex         = 0x06,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x02,
        .mNextSceneIndex    = SceneIndex_f_hyral,
        .mNextRoomIndex     = 0x06,
        .mNextSpawnIndex    = 0x04,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x004A,
        .mFlag              = AdventureFlag_ObtainedEngineerCertificate,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_SpiritTowerSplit
        .mUnk_00            = "d04_01",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x03,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x03,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x02,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x04,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x004B,
        .mFlag              = AdventureFlag_WatchedSpiritTowerSplitCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d04_02
        .mUnk_00            = "d04_02",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x02,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x04,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x03,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x05,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x004C,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_d04_03
        .mUnk_00            = "d04_03",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x03,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x05,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x03,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x06,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x004D,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d04_04
        .mUnk_00            = "d04_04",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x03,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x06,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x03,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x07,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0062,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d04_05
        .mUnk_00            = "d04_05",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x03,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x07,
        .mNextSceneIndex    = SceneIndex_f_hyral,
        .mNextRoomIndex     = 0x03,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0062,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d05_01
        .mUnk_00            = "d05_01",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x03,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x08,
        .mNextSceneIndex    = SceneIndex_d_main_f,
        .mNextRoomIndex     = 0x01,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x09,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x004E,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_FirstAnjeanMeeting
        .mUnk_00            = "d06_01",
        .mSceneIndex        = SceneIndex_d_main_f,
        .mRoomIndex         = 0x01,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x09,
        .mNextSceneIndex    = SceneIndex_d_main_f,
        .mNextRoomIndex     = 0x01,
        .mNextSpawnIndex    = 0x04,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x004F,
        .mFlag              = AdventureFlag_MetAnjeanFirstTime,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_FirstPhantomPossession
        .mUnk_00            = "d07_01",
        .mSceneIndex        = SceneIndex_d_main,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x02,
        .mCutsceneIndex     = 0x0A,
        .mNextSceneIndex    = SceneIndex_d_main,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x02,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0050,
        .mFlag              = AdventureFlag_WatchedFirstPhantomPossessionCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_ForestTempleCompleted
        .mUnk_00            = "d08_01",
        .mSceneIndex        = SceneIndex_b_forest,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x0B,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x01,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x0C,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0051,
        .mFlag              = AdventureFlag_WatchedForestTempleCompletedCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d08_02
        .mUnk_00            = "d08_02",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x01,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x0C,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x02,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x0D,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0052,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_d08_03
        .mUnk_00            = "d08_03",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x02,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x0D,
        .mNextSceneIndex    = SceneIndex_b_forest,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x02,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0053,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_BlizzardTempleCompleted
        .mUnk_00            = "d09_01",
        .mSceneIndex        = SceneIndex_b_snow,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x0E,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x06,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x0F,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0054,
        .mFlag              = AdventureFlag_WatchedBlizzardTempleCompletedCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d09_02
        .mUnk_00            = "d09_02",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x06,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x0F,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x07,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x10,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0055,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_d09_03
        .mUnk_00            = "d09_03",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x07,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x10,
        .mNextSceneIndex    = SceneIndex_b_snow,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0053,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_MarineTempleCompleted
        .mUnk_00            = "d10_01",
        .mSceneIndex        = SceneIndex_b_water,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x01,
        .mCutsceneIndex     = 0x11,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x04,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x12,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0056,
        .mFlag              = AdventureFlag_WatchedMarineTempleCompletedCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d10_02
        .mUnk_00            = "d10_02",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x04,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x12,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x05,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x13,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0057,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_d10_03
        .mUnk_00            = "d10_03",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x05,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x13,
        .mNextSceneIndex    = SceneIndex_b_water,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x01,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0053,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_StavenInTOSAfterFireGlyph
        .mUnk_00            = "d11_01",
        .mSceneIndex        = SceneIndex_d_main,
        .mRoomIndex         = 0x0F,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x14,
        .mNextSceneIndex    = SceneIndex_d_main_f,
        .mNextRoomIndex     = 0x01,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x15,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0061,
        .mFlag              = AdventureFlag_MetStavenInTOSAfterFireGlyphCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d11_02
        .mUnk_00            = "d11_02",
        .mSceneIndex        = SceneIndex_d_main_f,
        .mRoomIndex         = 0x01,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x15,
        .mNextSceneIndex    = SceneIndex_d_main_f,
        .mNextRoomIndex     = 0x01,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x004F,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_MountainTempleCompleted
        .mUnk_00            = "d12_01",
        .mSceneIndex        = SceneIndex_b_flame,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x16,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x08,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x17,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0058,
        .mFlag              = AdventureFlag_WatchedMountainTempleCompletedCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d12_02
        .mUnk_00            = "d12_02",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x08,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x17,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x02,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x18,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0059,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_d12_03
        .mUnk_00            = "d12_03",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x09,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x18,
        .mNextSceneIndex    = SceneIndex_b_flame,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x01,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0053,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_d13_01
        .mUnk_00            = "d13_01",
        .mSceneIndex        = SceneIndex_b_deago,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x02,
        .mCutsceneIndex     = 0x19,
        .mNextSceneIndex    = SceneIndex_b_deago,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005A,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_StavenPostBattle
        .mUnk_00            = "d14_01",
        .mSceneIndex        = SceneIndex_b_deago,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x1A,
        .mNextSceneIndex    = SceneIndex_b_deago,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x03,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005A,
        .mFlag              = AdventureFlag_WatchedStavenPostBattleCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_MalladusOnTOSSummit
        .mUnk_00            = "d15_01",
        .mSceneIndex        = SceneIndex_d_main_a,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x1B,
        .mNextSceneIndex    = SceneIndex_d_main_a,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x1C,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005B,
        .mFlag              = AdventureFlag_WatchedMalladusOnTOSSummitCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d15_02
        .mUnk_00            = "d15_02",
        .mSceneIndex        = SceneIndex_d_main_a,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x1C,
        .mNextSceneIndex    = SceneIndex_f_passenger,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x1D,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005B,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d16_01
        .mUnk_00            = "d16_01",
        .mSceneIndex        = SceneIndex_f_passenger,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x1D,
        .mNextSceneIndex    = SceneIndex_f_passenger,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005C,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_LokomoSword
        .mUnk_00            = "d17_01",
        .mSceneIndex        = SceneIndex_f_passenger,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x1E,
        .mNextSceneIndex    = SceneIndex_t_area2,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x07,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005C,
        .mFlag              = AdventureFlag_WatchedLokomoSwordCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d18_01
        .mUnk_00            = "d18_01",
        .mSceneIndex        = SceneIndex_f_passenger,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x1F,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x0A,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x20,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005C,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d19_01
        .mUnk_00            = "d19_01",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x0A,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x20,
        .mNextSceneIndex    = SceneIndex_b_last1,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005D,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d20_01
        .mUnk_00            = "d20_01",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x0A,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x21,
        .mNextSceneIndex    = SceneIndex_b_last2,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x22,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005D,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d20_02
        .mUnk_00            = "d20_02",
        .mSceneIndex        = SceneIndex_b_last2,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x22,
        .mNextSceneIndex    = SceneIndex_b_last2,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x23,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0060,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d20_03
        .mUnk_00            = "d20_03",
        .mSceneIndex        = SceneIndex_b_last2,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x23,
        .mNextSceneIndex    = SceneIndex_b_last2,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0060,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d21_01
        .mUnk_00            = "d21_01",
        .mSceneIndex        = SceneIndex_b_last2,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x24,
        .mNextSceneIndex    = SceneIndex_f_hyral,
        .mNextRoomIndex     = 0x05,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x25,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x002D,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d23_01
        .mUnk_00            = "d23_01",
        .mSceneIndex        = SceneIndex_f_hyral,
        .mRoomIndex         = 0x05,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x25,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x00,
        .mNextIsCS          = true,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005E,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d23_02
        .mUnk_00            = "d23_02",
        .mSceneIndex        = SceneIndex_f_hyral,
        .mRoomIndex         = 0x05,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x26,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x00,
        .mNextIsCS          = true,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005E,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_d23_03
        .mUnk_00            = "d23_03",
        .mSceneIndex        = SceneIndex_f_hyral,
        .mRoomIndex         = 0x05,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x27,
        .mNextSceneIndex    = SceneIndex_demo_train,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x00,
        .mNextIsCS          = true,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005E,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_SpiritPipes
        .mUnk_00            = "d24_01",
        .mSceneIndex        = SceneIndex_f_hyral,
        .mRoomIndex         = 0x05,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x28,
        .mNextSceneIndex    = SceneIndex_f_hyral,
        .mNextRoomIndex     = 0x05,
        .mNextSpawnIndex    = 0x01,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x005F,
        .mFlag              = AdventureFlag_ObtainedSpiritPipes,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
    {
        // CutsceneIndex_ForestTracksRestoredFromGlyph
        .mUnk_00            = "d25_01",
        .mSceneIndex        = SceneIndex_demo_train,
        .mRoomIndex         = 0x02,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x29,
        .mNextSceneIndex    = SceneIndex_d_main,
        .mNextRoomIndex     = 0x02,
        .mNextSpawnIndex    = 0x01,
        .mNextCutsceneIndex = CutsceneIndex_None,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x00,
        .mUnk_0E            = 0x0053,
        .mFlag              = AdventureFlag_ForestTracksRestoredFromGlyphCS,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 1,
        .mUnk_18            = 0,
    },
    {
        // CutsceneIndex_d26_01
        .mUnk_00            = "d26_01",
        .mSceneIndex        = SceneIndex_b_last2,
        .mRoomIndex         = 0x00,
        .mSpawnIndex        = 0x00,
        .mCutsceneIndex     = 0x2A,
        .mNextSceneIndex    = SceneIndex_b_last2,
        .mNextRoomIndex     = 0x00,
        .mNextSpawnIndex    = 0x00,
        .mNextCutsceneIndex = 0x24,
        .mNextIsCS          = false,
        .mUnk_0D            = 0x01,
        .mUnk_0E            = 0x0060,
        .mFlag              = AdventureFlag_None,
        .mUnk_12            = 0x0000,
        .mUnk_14            = 0,
        .mUnk_18            = 1,
    },
};

CutsceneParamsEntry *Cutscene_GetParamEntry(s32 csIndex) {
    return (CutsceneParamsEntry *) &gCSParamsEntries[csIndex];
}

s32 func_ov000_020a7840(unk32 param1) {}

bool Cutscene_IsAdventureFlagSet(s32 csIndex) {
    CutsceneParamsEntry *pEntry = Cutscene_GetParamEntry(csIndex);

    if (pEntry->mFlag == AdventureFlag_None) {
        return false;
    }

    return GET_FLAG(data_027e09b8->mAdventureFlags, pEntry->mFlag);
}
